stages:
  load_data:
    cmd: python scripts/load_data.py data/02_processed/olist_sales_with_payments.csv data/02_processed/olist_sum_sales_with_payments.csv
    deps:
    - scripts/load_data.py 
    - data/01_raw/olist_customers_dataset.csv 
    - data/01_raw/olist_geolocation_dataset_latlon.csv 
    - data/01_raw/olist_geolocation_dataset_state.csv
    - data/01_raw/olist_order_items_dataset.csv 
    - data/01_raw/olist_order_payments_dataset.csv
    - data/01_raw/olist_product_category_name_translation.csv 
    - data/01_raw/olist_products_dataset.csv
    - data/01_raw/olist_sellers_dataset.csv 
    - data/01_raw/olist_orders_dataset.csv
    - conf/catalog.yml 
    - conf/params.yml
    outs:
    - data/02_processed/olist_sales_with_payments.csv
    - data/02_processed/olist_sum_sales_with_payments.csv 
  
  processing:
    cmd: python3 scripts/processing.py python3 scripts/split.py
    deps:
    - data/02_processed/olist_sales_with_payments.csv
    - data/02_processed/olist_sum_sales_with_payments.csv 
    - conf/catalog.yml 
    - conf/params.yml 
    - src/utils.py
    
    
  train:
    cmd: python3 scripts/train_sarima.py 
    deps:
    - data/02_processed/olist_sales_with_payments.csv
    - data/02_processed/olist_sum_sales_with_payments.csv 
    params:
    - conf/catalog.yml 
    - conf/params.yml 
    - src/utils.py
    - src/sarima.py
    - src/metrics.py
    outs:
     - data/04_results/olist/exp1_sarima_bed_bath_table.csv
     - data/04_results/olist/exp1_sarima_health_beauty.csv
     - data/04_results/olist/exp1_sarima_sports_leisure.csv
     - data/04_results/olist/exp1_sarima_telephony.csv
     - data/04_results/olist/exp1_sarima_watches_gifts.csv
     - data/04_results/olist/exp1_sarima_housewares.csv