stages:
  featurize:
    cmd: python3 src/featurize.py data/01_raw/interne
    deps:
    - data/raw
    - src/featurize.py
    params:
    - featurize.max_row_limit
    - featurize.window_size
    outs:
    - data/featurize
  train:
    cmd: python3 src/train.py data/featurize data/01_raw/predection
    deps:
    - data/featurize
    - src/model.py
    - src/train.py
    params:
    - featurize.window_size
    - train.batch_size
    - train.epochs
    - train.hidden_size
    outs:
    - data/predictions
  validate:
    cmd: python3 src/validate.py data/featurize data/predictions metrics.json
    deps:
    - data/featurize
    - data/predictions
    - src/validate.py
    params:
    - featurize.window_size
    metrics:
    - metrics.json:
        cache: false