name: CML & DVC
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Experiment
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo -H  pip3 install -r requirements.txt
          pip3 install --no-cache-dir --upgrade awscli pandas boto3  requests fsspec s3fs tabulate
          pip3 install dvc[s3]
          dvc pull  --run-cache        # Pull data & run-cache from S3
          dvc repro                        # Reproduce pipeline
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Metrics" >> report.md
          cat data/04_results/olist/exp1_prophet_bed_bath_table.csv>> report.md
          echo "## Data viz from S3" >> report.md
          cml-send-comment report.md
          