name: train-my-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v3
    - name: 'cml '
      shell: bash 
      run: |
       python -m pip install --upgrade pip
       sudo -H  pip install -r requirements.txt
       #Install requirements
       python ./scripts/load_data.py 