name: train-my-model
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v3
    - name: 'cml '
      shell: bash 
      run: |
       python -m pip install --upgrade pip
       sudo -H  pip install -r requirements.txt
       #Install requirements
       python ./scripts/load_data.py 
       echo "## Model metrics" > report.md
       cat exp1_prophet_bed_bath_table.csv >> report.md
          
       echo "## Data viz" >> report.md
       cml-publish olist_xgb_exp1_bed_bath_table.png --md >> report.md
       
          
       cml-send-comment report.md
