name: Python Package and Test
on: 
   push :
jobs:
   Build:
        runs-on: ubuntu-22.04 
        strategy:
          matrix:
            python-version: [3.7]
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade setuptools pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
   Test:
        needs: [build]
        runs-on: [ubuntu-latest]
        steps:
        - uses: actions/checkout@v2
        - name: Test with pytest
          run: |
            pip install pytest black
            pytest
        - name: Python Black
          run:  black . --check