name: Test 2 jobs in github actions
on: 
   push :
jobs:
  prepare_env:
      runs-on: ubuntu-18.04
      strategy:
          matrix:
            python-version: [3.7]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
             python -m pip install --upgrade setuptools pip
             pip install pytest black
             if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  testing:
      needs: [prepare_env]
      runs-on: [ubuntu-latest]
      steps:
        - uses: actions/checkout@v2
          name: Set upp Python ${{ matrix.python-version }}
          with:
            python-version: ${{ matrix.python-version }}
        - name: Test with pytest
          run: python3 -m pytest
        - name: Python3 Black
          run:  black . --check
