name: model-training-evaluate
on: [push]
jobs:
  Retrain_model:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run Experiments
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo -H  pip3 install -r requirements.txt
          pip3 install --no-cache-dir --upgrade awscli pandas boto3  requests fsspec s3fs tabulate
            # Pull data & run-cache from IBM COS and reproduce pipeline
          dvc pull --run-cache
          dvc repro
          dvc push

          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff main --show-md >> report.md
          cml-send-comment report.md




      
          