name: model-training-evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
       - uses: actions/checkout@v2
       - name: 'dvc repro from S3'
         shell: bash
         env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: | 
          # Install requirement
          python -m pip install --upgrade setuptools pip
          sudo -H  pip install -r requirements.txt
          pip install  awscli pandas boto3 
          pip install dvc[s3]
          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache
          dvc repro
          # Report metrics
          echo "## Metrics" >> report.md
          cat data/04_results/olist/exp1_prophet_bed_bath_table.csv>> report.md
          echo "## Data viz from S3" >> report.md
          cml-send-comment report.md
          
         
          
