name: model-training-evaluate
on: 
  push:
    branches: [ main ]
jobs:
    reproduce_dvc:
      runs-on: [ubuntu-latest]
      container: docker://dvcorg/cml-py3:latest
      steps:
       - name: Checkout
       - uses: actions/checkout@v2
         name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-southeast-1
       - name: 'dvc repro from S3'
         shell: bash
         env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
         run: | 
          python -m pip install --upgrade setuptools pip
          sudo -H  pip install -r requirements.txt
          pip install dvc[s3]
          python -m pip install awscli
          dvc pull --run-cache
          dvc repro
          echo "## Metrics" >> report.md
          cat data/04_results/olist/exp1_prophet_bed_bath_table.csv>> report.md
          echo "## Data viz from S3" >> report.md
          cml-send-comment report.md
          
         
          
