name: model-training-evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train and Evaluate model'
        shell: bash
        run: |
           pip install -r requirements.txt
          #Install requirements
          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache
          dvc repro
          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff main --show-md >> report.md
          # Publish confusion matrix diff
          echo -e "## Plots\n### ROC Curve" >> report.md
          cml-publish ./results/roc_curve.png --md >> report.md
          echo -e "\n### Precision and Recall Curve" >> report.md
          cml-publish ./results/precision_recall_curve.png --md >> report.md
          cml-send-comment report.md